# This is a basic workflow to help you get started with Actions

name: My-GitHubAction-Workbox

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  file_caching:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Generate new workbox.
        run: |
          #!/bin/sh
          if workbox generateSW workbox-config.js ; then
            git add sw.js
            exit 0
          else
            echo "Cannot generate sw.js"
            echo "Aborting"
          fi
 
